FROM ubuntu:jammy

RUN touch /etc/localtime
ENV TZ=Europe/Moscow

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y openssh-server mc nano locales software-properties-common tzdata git curl supervisor
RUN apt-get install -y libc-client-dev libkrb5-dev nginx logrotate mariadb-client rsync
RUN add-apt-repository ppa:ondrej/php && apt-get update
RUN apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-fpm php8.2-mysql php8.2-zip php8.2-gd php8.2-mbstring php8.2-curl php8.2-xml php8.2-bcmath php8.2-xdebug php8.2-sqlite3

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs build-essential && npm install -g npm@9
RUN npm i -g laravel-echo-server

ARG USER_ID=2000
ARG GROUP_ID=2000
RUN groupadd -g ${GROUP_ID} www
RUN useradd -u ${USER_ID} -ms /bin/bash -g www www
RUN usermod -a -G root www

RUN localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8
ENV LANG ru_RU.UTF-8

RUN mkdir /run/sshd && chown -R www:www /etc/ssh
RUN mkdir /home/www/.ssh && chown -R www:www /home/www/.ssh

RUN php -r "readfile('https://getcomposer.org/installer');" | php
RUN chmod 755 composer.phar
RUN mv composer.phar /usr/bin/composer

RUN mkdir -pv /var/www/html && chown -R www:www /var/www
RUN mkdir -pv /run/php && chown -R www:www /run/php
RUN chmod -R 775 /var/log
RUN mkdir -pv /var/log/php && chown -R www:www /var/log/php
RUN chown -R www:www /var/log/supervisor
RUN chown -R www:www /var/log/nginx

COPY ./logrotate.d /etc/logrotate.d
COPY ./.bashrc /home/www/.bashrc
RUN chown www:www /home/www/.bashrc
RUN chmod 664 /etc/environment
COPY ./ssh_conf /etc/ssh
COPY ./supervisor_conf /etc/supervisor

COPY ./php_conf/apache2/php.ini /etc/php/8.2/apache2/php.ini
COPY ./php_conf/cli/php.ini /etc/php/8.2/cli/php.ini
COPY ./php_conf/fpm/php.ini /etc/php/8.2/fpm/php.ini
COPY ./php_conf/fpm/pool.d /etc/php/8.2/fpm/pool.d
COPY ./php_conf/fpm/php-fpm.conf /etc/php/8.2/fpm/php-fpm.conf

COPY ./nginx_conf /etc/nginx
RUN chown -R www:www /etc/ssh && chown -R www:www /etc/supervisor && chown -R www:www /etc/php/8.2 && chown -R www:www /etc/nginx

USER www
RUN composer global require laravel/installer
RUN cd /var/www && rm -rf html && /home/www/.config/composer/vendor/bin/laravel new html
RUN cd /var/www/html && composer require laravel/ui && composer require doctrine/dbal
RUN cd /var/www/html && composer require laravel/dusk && php artisan dusk:install
RUN cd /var/www/html && composer require --dev beyondcode/laravel-dump-server
RUN cd /var/www/html && npm i && npm run build
COPY ./web/html/laravel-echo-server.json /var/www/html/laravel-echo-server.json
COPY ./web/html/laravel-echo-server.json.example /var/www/html/laravel-echo-server.json.example

USER root
RUN chmod -R 0755 /var/www/html/vendor/laravel/dusk/bin/
RUN chown -R www:www /var/www

USER www
WORKDIR /var/www/html
COPY ./entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]

